export const ERROR_CODES = {
  INVALID_INPUT: "ERR_INVALID_INPUT",
  SOURCE_NOT_FOUND: "ERR_SOURCE_NOT_FOUND",
  REPO_FETCH_FAILED: "ERR_REPO_FETCH_FAILED",
  COORDINATE_PARSE_FAILED: "ERR_COORDINATE_PARSE_FAILED",
  DB_FAILURE: "ERR_DB_FAILURE",
  DECOMPILER_UNAVAILABLE: "ERR_DECOMPILER_UNAVAILABLE",
  DECOMPILER_FAILED: "ERR_DECOMPILER_FAILED",
  FILE_NOT_FOUND: "ERR_FILE_NOT_FOUND",
  LIMIT_EXCEEDED: "ERR_LIMIT_EXCEEDED",
  INVALID_LINE_RANGE: "ERR_INVALID_LINE_RANGE",
  ARTIFACT_RESOLUTION_FAILED: "ERR_ARTIFACT_RESOLUTION_FAILED",
  MAPPING_NOT_APPLIED: "ERR_MAPPING_NOT_APPLIED",
  PROVENANCE_INCOMPLETE: "ERR_PROVENANCE_INCOMPLETE",
  CONTEXT_UNRESOLVED: "ERR_CONTEXT_UNRESOLVED",
  JAR_NOT_FOUND: "ERR_JAR_NOT_FOUND",
  VERSION_NOT_FOUND: "ERR_VERSION_NOT_FOUND",
  CLASS_NOT_FOUND: "ERR_CLASS_NOT_FOUND",
  NAMESPACE_MISMATCH: "ERR_NAMESPACE_MISMATCH",
  MAPPING_UNAVAILABLE: "ERR_MAPPING_UNAVAILABLE",
  DECOMPILE_DISABLED: "ERR_DECOMPILE_DISABLED",
  NBT_PARSE_FAILED: "ERR_NBT_PARSE_FAILED",
  NBT_INVALID_TYPED_JSON: "ERR_NBT_INVALID_TYPED_JSON",
  JSON_PATCH_INVALID: "ERR_JSON_PATCH_INVALID",
  JSON_PATCH_CONFLICT: "ERR_JSON_PATCH_CONFLICT",
  NBT_ENCODE_FAILED: "ERR_NBT_ENCODE_FAILED",
  NBT_UNSUPPORTED_FEATURE: "ERR_NBT_UNSUPPORTED_FEATURE",
  REGISTRY_GENERATION_FAILED: "ERR_REGISTRY_GENERATION_FAILED",
  JAVA_UNAVAILABLE: "ERR_JAVA_UNAVAILABLE",
  JAVA_PROCESS_FAILED: "ERR_JAVA_PROCESS_FAILED",
  REMAP_FAILED: "ERR_REMAP_FAILED",
  REMAPPER_UNAVAILABLE: "ERR_REMAPPER_UNAVAILABLE",
  INTERNAL: "ERR_INTERNAL"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ErrorDetails {
  [key: string]: unknown;
}

export interface ErrorPayload {
  code: ErrorCode;
  message: string;
  details?: ErrorDetails;
}

export class AppError extends Error {
  public readonly code: ErrorCode;
  public readonly details?: ErrorDetails;

  constructor(payload: ErrorPayload) {
    super(payload.message);
    this.name = "AppError";
    this.code = payload.code;
    this.details = payload.details;
  }
}

export const createError = (payload: ErrorPayload): AppError => new AppError(payload);

export const isAppError = (value: unknown): value is AppError => {
  return value instanceof Error && (value as AppError).code !== undefined;
};
